### ISSUE TITLE
Enhancement: cache settings

### ISSUE THREAD

**Issue by JennieJi** [tanhauhau/babel-ast-explorer#2]
Thinging of save settings to localstorage.

**Comment by kenrick95** [comment]
It's already stored in URL, right?

**Comment by JennieJi** [comment]
but I don't always save url?

Best Regards,
Jennie Ji

________________________________

**Comment by tanhauhau** [comment]
i guess you meant the behavior like the flow repl right?

**Comment by JennieJi** [comment]
@tanhauhau and the other AST explorer, cuz I find it's quite annoying every time I have to choose version and display options again

**Comment by tanhauhau** [comment]
Understood. We can keep the settings in the localstorage then.

@JennieJi  you wanna help contribute by implementing this enhancement?

**Comment by JennieJi** [comment]
@tanhauhau sure
